//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_in_parking
    {
        public int c_id { get; set; }
        public int c_car_id { get; set; }
        public int c_parkingId { get; set; }
        public System.DateTime c_date_start { get; set; }
        public Nullable<System.DateTime> c_date_end { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Parking Parking { get; set; }
    }
}
