//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingEntities : DbContext
    {
        public ParkingEntities()
            : base("name=ParkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Car_in_parking> Car_in_parking { get; set; }
        public virtual DbSet<Criterion> Criteria { get; set; }
        public virtual DbSet<Parking_owner> Parking_owner { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<Parkings_of_owner> Parkings_of_owner { get; set; }
        public virtual DbSet<Setting_user> Setting_user { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
