//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking()
        {
            this.Car_in_parking = new HashSet<Car_in_parking>();
            this.Parkings_of_owner = new HashSet<Parkings_of_owner>();
        }
    
        public int p_Id { get; set; }
        public string p_Name { get; set; }
        public string p_Addess { get; set; }
        public decimal p_Long { get; set; }
        public decimal p_Lat { get; set; }
        public int p_ParkingsNum { get; set; }
        public int p_EmptyParkings { get; set; }
        public Nullable<bool> p_For_few_days { get; set; }
        public string p_Description { get; set; }
        public int p_PricesHour { get; set; }
        public string p_API_Details { get; set; }
        public string p_BankDetails { get; set; }
        public System.TimeSpan p_ActivityHoursTill { get; set; }
        public System.TimeSpan p_ActivityHoursEnd { get; set; }
        public string p_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car_in_parking> Car_in_parking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parkings_of_owner> Parkings_of_owner { get; set; }
    }
}
