//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parkings_of_owner
    {
        public int op_id { get; set; }
        public int op_parking_id { get; set; }
        public Nullable<int> op_owner_id { get; set; }
    
        public virtual Parking_owner Parking_owner { get; set; }
        public virtual Parking Parking { get; set; }
    }
}
