//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting_user
    {
        public int s_user_id { get; set; }
        public Nullable<int> s_choose_criterion { get; set; }
        public Nullable<int> s_range { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual user user { get; set; }
    }
}
